### ISSUE TITLE
bug: reddit 'start' button doesnt work

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-extension#20]
reddit 'start' button doesnt work.

- [ ] fix so it works on reddit

---

misc edit: 

- [ ] change "Clapper" to "SERP Extension"

<img width="515" alt="Screenshot 2024-03-24 at 19 46 02" src="https://github.com/serpcompany/serp-extension/assets/45643901/dc74c63f-58a0-4f77-9275-e2d4e19a7ac6">

**Comment by mittalyashu** [comment]
As the [Reddit script logic](https://github.com/serpcompany/serp-extension/blob/main/js/reddit.js) works only on older designs.

I have shared about this in the [original PR](https://github.com/serpcompany/serp-extension/pull/15) as well.

> As Reddit released their new UI design, the current logic will only work on [older Reddit design](https://new.reddit.com/) (Year: 2018 - 2023)

**Comment by mittalyashu** [comment]
I should have posted screenshot to give a reference of what I meant by new/old Reddit UI.

_Not sure, if the new reddit UI has been rolled out in your region._

| Old UI | New UI |
| --- | --- |
| ![CleanShot 2024-03-26 at 00 47 51@2x](https://github.com/serpcompany/serp-extension/assets/29014463/a0623fa6-3063-4dc8-a4bf-9e1d71d6b5e0) | ![CleanShot 2024-03-26 at 00 47 27@2x](https://github.com/serpcompany/serp-extension/assets/29014463/266a5129-4d20-4cd6-b0b3-8b520c1985eb) |

**Comment by devinschumacher** [comment]
@mittalyashu look: https://www.loom.com/share/0a28a346e4044078a3c28edd0f320405
