### ISSUE TITLE
serp extension - add the functionality of 'see robots' to the serp extension

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-extension#22]
- [x] add the functionality of 'see robots' to the serp extension
- [x] change the extension icon to the white serp logo (so we can change its colors like the 'see robots' extension does) -- file below

---

File: serp logo (in .png and .svg)

![SERP Arrow - White - Up](https://github.com/serpcompany/public/assets/45643901/4a4e846b-5d20-480c-a1a0-a31bd3629cdd)

![SERP Arrow - White - Up](https://github.com/serpcompany/public/assets/45643901/f0d0fb01-03ac-496d-a98a-374e831fb1e9)

**Comment by mittalyashu** [comment]
How much is the bounty on this issue?

**Comment by devinschumacher** [comment]
@mittalyashu we can just do hourly right now - ping me in slack and we will work it out

**Comment by mittalyashu** [comment]
Marking this issue as closed 🙂
