### ISSUE TITLE
serp extension - add functionality of 'notifier for github' to serp extension

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-extension#28]
serp extension - add functionality of 'notifier for github' to serp extension

- [extension chrome store](https://chromewebstore.google.com/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn)
- [extension repo](https://github.com/sindresorhus/notifier-for-github)

- [ ] duplicate the functionality into the github.comserpcompany/serp-extension -- only change to make is that the "notification icon" on the extension should be color RED (not blue)

**Comment by mittalyashu** [comment]
**Update:** Started working on it
