### ISSUE TITLE
notification bug

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-extension#50]
- [ ] see https://www.loom.com/share/5f11ca22a8f7487dabe829bc146f5f67

**Comment by mittalyashu** [comment]
@devinschumacher It automatically hits the API every 3 minutes before you see the updated in the Chome extension.

Should I decrease the time interval?

**Comment by devinschumacher** [comment]
@mittalyashu didnt we say the other one did it every minute?

i also think it had some kind of PUSH resposne bc whenever i cleared my stuff it would clear too

**Comment by devinschumacher** [comment]
@mittalyashu  

- [ ] this part doesnt update either:


<img width="623" alt="image" src="https://github.com/serpcompany/serp-extension/assets/45643901/a6260f43-83af-4d19-896b-0bbd900a0537">
